### ISSUE TITLE
Feature Request | Ignore Non-Players

### ISSUE THREAD

**Issue by micartey** [micartey/Cardinal-Anticheat#194]
### Information

Ignore humanoid mobs if they are not players

### Reason

Intervention with game modes

### Additional information

Can be disabled via a config value

**Comment by micartey** [comment]
Can be disabled in Release 4.2.0

```yml
  # Entity types that will be checked for (affects only combat checks)
  targets:
    # Set this to false if players cannot attack each other
    player: true
    # Set this to flase if villagers being attacked is of no importance
    villager: true
    # Set this to false if mobs humanoid mobs being attacked is of no importance
    mobs: true
```
